In [1]:
import pandas as pd

In [ ]:
df = pd.read_csv('results.csv')
df_ours = df[df['group'] == 4]
df_ours

,cake_path,children,group,size_span,ratios_stdev,seconds
3,cakes/tournament/4444.csv,5,4,0.1872,4.6475,15.8492
13,cakes/tournament/4444.csv,7,4,0.1284,4.1413,24.5275
23,cakes/tournament/4444.csv,11,4,0.0817,7.0428,194.6557
33,cakes/tournament/butterfly.csv,13,4,-1.0000,-1.0000,300.0000
43,cakes/tournament/butterfly.csv,18,4,-1.0000,-1.0000,300.0000
...,...,...,...,...,...,...
1303,cakes/tournament/rectangle.csv,12,4,0.0659,13.5535,5.6989
1313,cakes/tournament/rectangle.csv,18,4,-1.0000,-1.0000,300.0000
1323,cakes/tournament/squeeze.csv,8,4,0.0710,9.7085,30.1239
1333,cakes/tournament/squeeze.csv,10,4,0.0929,11.4860,39.6555
1343,cakes/tournament/squeeze.csv,16,4,0.0603,11.4624,71.9247

In [13]:
for player in range(1, 11):
    df_player = df[df['group'] == player]
    print(f"Player {player}:")
    print(len(df_player[df_player['ratios_stdev'] == -1]))

Player 1:
10
Player 2:
24
Player 3:
10
Player 4:
47
Player 5:
10
Player 6:
11
Player 7:
26
Player 8:
74
Player 9:
58
Player 10:
10

In [11]:
print(len(df_ours[df_ours['size_span'] == -1]))

df_ours[df_ours['size_span'] == -1]['cake_path'].value_counts()

47

cake_path
cakes/tournament/butterfly.csv                              3
cakes/tournament/players/player1/crown.csv                  3
cakes/tournament/players/player6/parallelogram.csv          3
cakes/tournament/players/player10/HBD.csv                   3
cakes/tournament/players/player2/heart.csv                  3
cakes/tournament/players/player2/yankees.csv                3
cakes/tournament/players/player4/hilbert_challenging.csv    2
cakes/tournament/players/player9/group9gon.csv              2
cakes/tournament/players/player9/Cross.csv                  2
cakes/tournament/players/player5/simple.csv                 2
cakes/tournament/players/player5/complex.csv                2
cakes/tournament/players/player4/square.csv                 2
cakes/tournament/rectangle.csv                              2
cakes/tournament/players/player2/princess.csv               2
cakes/tournament/horseshoe.csv                              2
cakes/tournament/figure_eight.csv                           1
cakes/tournament/players/player4/rocket_creative.csv        1
cakes/tournament/players/player3/star.csv                   1
cakes/tournament/players/player5/cool.csv                   1
cakes/tournament/players/player10/weirdS.csv                1
cakes/tournament/players/player1/star.csv                   1
cakes/tournament/players/player8/star.csv                   1
cakes/tournament/players/player1/cat.csv                    1
cakes/tournament/players/player9/Penguin.csv                1
cakes/tournament/players/player9/hard.csv                   1
cakes/tournament/players/player4/rectangle.csv              1
Name: count, dtype: int64